version: '3.3'

services:
  web:
    build: ./student
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./student/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student123
      - POSTGRES_DB=student

volumes:
  postgres_data:
